apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z4ui3xsw0-go 
  janus-idp.io/tekton: z4ui3xsw0-go
  backstage.io/kubernetes-id: z4ui3xsw0-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z4ui3xsw0-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml